servers = {
    "corex": {"install": "USAGE:", "delete": "", "port": "1500"},
    "mail_forwarder": {"install": "", "delete": "", "port": ""},
    "etcd": {"install": "", "delete": "", "port": ""},
    "zdb": {"install": "", "delete": "", "port": ""},
    "tmux": {
        "install": "",
        "delete": "",
        "port": "",
        "session": "",
        "list_sessions": "",
        "new_session": "",
        "kill_server ": "",
        "kill_session": "",
        "execute": "",
    },
    "odoo": {
        "install": "",
        "delete": "",
        "port": "",
        "databases_create": "",
        "databases_list ": "",
        "database_import": "",
        "database_export": "",
        "databases_reset": "",
        "edit": "",
    },
    "sonic": {"install": "", "delete": "", "port": ""},
    "sanic": {"install": "", "delete": "", "port": ""},
    "startupcmd": {"install": "", "delete": "", "port": "", "startupcmd": ""},
    "capacity": {},
    "flask": {"install": "", "port": ""},
    "errbot": {},
    "gedis_websocket": {},
    "sockexec": {"install": "", "delete": "", "port": ""},
}
