#! /usr/bin/env python3
from Jumpscale import j
import pprint
import click


@click.group()
def cli():
    pass


HELP = """

threebot tool
"""

@click.command()
def start():
    j.servers.threebot.start(background=True)
    print (" - Server started ok")



@click.command()
def help():
    print(HELP)



cli.add_command(start)
cli.add_command(help)

if __name__ == "__main__":
    cli()
