#! /usr/bin/env python3
import os
import sys
import click
import os


@click.group()
def cli():
    pass


try:
    from Jumpscale import j
except:
    for item in [
        "{DIR_HOME}/code/github/threefoldtech/jumpscaleX/Jumpscale",
        "/sandbox/code/github/threefoldtech/jumpscaleX/Jumpscale",
    ]:
        item = item.replace("$HOME", os.environ["HOME"])
        if os.path.exists(item) and item not in sys.path:
            sys.path.append(item)
    from Jumpscale import j


@click.command()
@click.option("-p", "--path", default=None, help="path to process")
@click.option("--all", is_flag=True, help="process all")
def process(path=None, all=False):
    """
    """
    git = j.clients.git.get(basedir=path)
    git.patchGitignore()
    revision, result = git.logChanges(all=all)
    print(result)
    git.logChangesRevisionSet(revision=revision)
    # j.shell()


# cli.add_command(scan)
cli.add_command(process)

if __name__ == "__main__":
    cli()
