#!/usr/bin/env python3

from Jumpscale import *

j.tools.bash.get().profile.locale_check()
import os
import click

os.environ["LC_ALL"] = "en_US.UTF-8"


@click.group()
def cli():
    pass


@click.command()
@click.option(
    "--name", default="system", help="specify which bcdb you want to delete, if not specified will use system"
)
@click.option("--all", is_flag=True, help="delete all")
def delete(name=None, all=False):
    if not name and all is False:
        name = "system"
    j.application.interactive = True

    def do(name):
        if name.lower() == "system":
            j.application.bcdb_system_destroy()
        else:
            bcdb = j.data.bcdb.get(name=name, reset=True)
            bcdb.destroy()

    if all:
        if j.tools.console.askYesNo("Are you sure you want to destroy all BCDB's"):
            _unlock()
            j.data.bcdb.threebot_stop()
            j.data.bcdb.destroy_all()

    else:
        if j.tools.console.askYesNo("Are you sure you want to destroy:%s" % name):
            _unlock(name)
            do(name)


@click.command()
@click.option("--name", help="specify which bcdb you want to unlock, if not specified will unlock all")
def unlock(name=None):
    _unlock(name=name)


def _unlock(name=None):
    base_path = j.core.tools.text_replace("{DIR_VAR}/bcdb/")
    instances = []
    if name:
        instances = [name]
    else:
        if j.sal.fs.exists(base_path):
            instances = [j.sal.fs.getBaseName(instance_path) for instance_path in j.sal.fs.listDirsInDir(base_path)]
    for instance in instances:
        lock_path = j.sal.fs.joinPaths(base_path, instance, "lock")
        if j.sal.fs.exists(lock_path):
            j.sal.fs.remove(lock_path)
            print(f"BCDB instance {instance} unlocked")


# @click.command()
# @click.option("--name", default=None, help="specify which bcdb you want to fix, if not specified will use all")
# def check(name=None):
#     """
#     will check and if issues found in index it will rebuild the index
#     :return:
#     """
#     j.application.check()
#     if not name:
#         j.shell()
#     j.shell()


@click.command()
def check(name=None):
    """
    will check the starting point for bcdb
    :return:
    """
    j.application.check()


@click.command()
@click.option("--name", default=None, help="specify which bcdb you want to rebuild, if not specified will use all")
def rebuild(name=None):
    """
    bcdb rebuild
    will erase the indexes and rebuild it from the BCDB original data
    :return:
    """

    j.data.bcdb.threebot_start()

    if not name:
        for bcdb in j.data.bcdb.instances.values():
            bcdb.index_rebuild()
    else:
        bcdb = j.data.bcdb.get(name=name, reset=False)
        bcdb.index_rebuild()


if __name__ == "__main__":
    cli.add_command(delete)
    cli.add_command(check)
    cli.add_command(rebuild)
    cli.add_command(unlock)

    cli()
