#!/usr/bin/env python3

from Jumpscale import *

# j.tools.bash.get().profile.locale_check()
import os
import click

os.environ["LC_ALL"] = "en_US.UTF-8"

# needs to become master !
j.data.bcdb._master_set(True)


@click.group()
def cli():
    pass


@click.command()
@click.option(
    "--name", default="system", help="specify which bcdb you want to delete, if not specified will use system"
)
@click.option("--all", is_flag=True, help="delete all")
@click.option("-f", "--force", is_flag=True, help="delete all")
def delete(name=None, all=False, force=False):
    if not name and all is False:
        name = "system"
    j.application.interactive = True

    def do(name):
        if name.lower() == "system":
            j.application.bcdb_system_destroy()
        else:
            bcdb = j.data.bcdb.get(name=name, reset=True)
            bcdb.destroy()

    if all:
        if force or j.tools.console.askYesNo("Are you sure you want to destroy all BCDB's"):
            # _unlock()
            try:
                j.data.bcdb.threebot_stop()
            except:
                pass
            j.data.bcdb.destroy_all()
            j.sal.fs.remove(j.core.tools.text_replace("{DIR_VAR}/codegen"))
            path_metaschema = j.core.tools.text_replace("{DIR_CFG}/schema_meta.msgpack")
            if j.sal.fs.exists(path_metaschema):
                j.sal.fs.remove(path_metaschema)

    else:
        if j.tools.console.askYesNo("Are you sure you want to destroy:%s" % name):
            # _unlock(name)
            do(name)

    # load your identity again
    # don't load in mem gives weird results
    j.core.tools.execute("j.me.configure(ask=False)", jumpscale=True, interactive=True)


@click.command()
def check(name=None):
    """
    will check the starting point for bcdb
    :return:
    """
    j.application.check()


@click.command()
@click.option("--name", default=None, help="specify which bcdb you want to rebuild, if not specified will use all")
def rebuild(name=None):
    """
    bcdb rebuild
    will erase the indexes and rebuild it from the BCDB original data
    :return:
    """

    j.data.bcdb.start_servers_threebot_zdb_sonic()

    if not name:
        for bcdb in j.data.bcdb.instances.values():
            # load all objects to make sure all models loaded
            bcdb.get_all()
            bcdb.index_rebuild()
    else:
        bcdb = j.data.bcdb.get(name=name, reset=False)
        # load all objects to make sure all models loaded
        bcdb.get_all()
        bcdb.index_rebuild()


if __name__ == "__main__":
    cli.add_command(delete)
    cli.add_command(check)
    cli.add_command(rebuild)

    cli()
