#! /usr/bin/env python3
from Jumpscale import j

j.tools.bash.get().profile.locale_check()
import click


@click.group()
def cli():
    pass


@click.command()
def list():
    """
    """
    j.tools.alerthandler.print()


@click.command()
def reset():
    """
    will erase the alerts in the DB
    """
    j.tools.alerthandler.reset()


@click.command()
def test():
    """
    a small test script
    """
    j.tools.alerthandler.test(delete=False)


@click.command()
def find():
    """
    find specific alerts

    """
    raise RuntimeError("not implemented")


@click.command()
def delete(cat="", message=""):
    """
    delete specific alerts
    """
    raise RuntimeError("not implemented")


cli.add_command(list)
cli.add_command(reset)
cli.add_command(test)
cli.add_command(find)
cli.add_command(delete)

if __name__ == "__main__":
    cli()
