#! /usr/bin/env python3
import click
from types import SimpleNamespace
from Jumpscale import j


def get_client(redis_host, redis_port, redis_secret):
    client = j.clients.logger.get("js_logs")
    if redis_host:
        client.redis_host = redis_host
    if redis_port:
        client.redis_port = redis_port
    if redis_secret:
        client.redis_secret = redis_secret

    return client


def common_options(function):
    click.option("--redis-host", default=None, help="redis host (defaults to localhost)")(function)
    click.option("--redis-port", default=6379, help="redis port (defaults to 6379)")(function)
    click.option("--redis-secret", default=None, help="redis secret (empty by default)")(function)
    click.option("-a", "--appname", default="init", help="application name")(function)
    return function


@click.group()
@common_options
@click.pass_context
def cli(ctx, redis_host, redis_port, redis_secret, appname):
    ctx.obj = SimpleNamespace()
    ctx.obj.client = get_client(redis_host, redis_port, redis_secret)
    ctx.obj.appname = appname


@cli.command()
@click.pass_obj
def tail(ctx_obj):
    """
    tail logs from session
    """
    ctx_obj.client.tail(appname=ctx_obj.appname)


if __name__ == "__main__":
    cli()
