#! /usr/bin/env python3
import click

from Jumpscale import j


def get_client(redis_host, redis_port, redis_secret):
    client = j.clients.logger.get("js_logs")
    if redis_host:
        client.redis_host = redis_host
    if redis_port:
        client.redis_port = redis_port
    if redis_secret:
        client.redis_secret = redis_secret

    return client


@click.group()
def cli():
    pass


def common_options(function):
    click.option("--redis-host", default=None, help="redis host (defaults to localhost)")(function)
    click.option("--redis-port", default=6379, help="redis port (defaults to 6379)")(function)
    click.option("--redis-secret", default=None, help="redis secret (empty by default)")(function)
    click.option("--timefrom", default=None, help="filter by date (epoch), defaults to -1h")(function)
    click.option("--timeto", default=None, help="filter by date (epoch), defaults to -1h")(function)
    click.option("--category", default=None, help="filter bycategory, defaults to -1h")(function)
    click.option("-a", "--appname", default="init", help="application name")(function)
    return function


@click.command()
@common_options
def tail(appname, category, timefrom, timeto, redis_host, redis_port, redis_secret):
    """
    tail logs from session
    """
    client = get_client(redis_host, redis_port, redis_secret)
    client.tail(appname)


@click.command()
@common_options
@click.option("--path", required=True, help="output file path")
def dump(redis_host, redis_port, redis_secret, path):
    """
    dump logs of session to file
    """
    client = get_client(redis_host, redis_port, redis_secret)
    client.dump(path)


cli.add_command(tail)
cli.add_command(dump)

if __name__ == "__main__":
    cli()
