#!/usr/bin/env python3
import sys
from argparse import ArgumentParser

from Jumpscale import j

if __name__ == "__main__":
    parser = ArgumentParser()
    parser.add_argument(
        "--with-xml", action="store_true", dest="xml_report", help="Enable xml report after finishing tests."
    )
    parser.add_argument("--xml-path", type=str, dest="xml_path", default="test.xml", help="xml file path.")
    parser.add_argument(
        "--xml-testsuite-name", type=str, dest="xml_testsuite_name", default="jsx_runner", help="xml testsuite name.",
    )
    parser.add_argument("-o", "--object", type=str, dest="obj", help="JSX object that contains tests.")
    parser.add_argument("-p", "--path", type=str, dest="path", default=".", help="Path that contains tests.")
    options = parser.parse_args()
    test_runner = j.baseclasses.testtools()
    test_runner._init_factory(
        xml_report=options.xml_report, xml_path=options.xml_path, xml_testsuite_name=options.xml_testsuite_name
    )

    if options.obj:
        run = test_runner._run_tests_from_object(obj=eval(options.obj))
    else:
        if ":" in options.path:
            if len(options.path.split(":")) is not 2:
                raise ValueError(f"{options.path} is not valid")
            else:
                path, test_name = options.path.split(":")
                run = test_runner._run_from_path(path, test_name)
        else:
            run = test_runner._run_from_path(options.path)
    sys.exit(run)
